import './globals.css'
import { Inter } from 'next/font/google'
import NavList from './components/navList'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Halvor\'s webpage',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"></meta>
      </head>
      <header>
        <NavList />
      </header>
      <body className={inter.className}>
        {children}
      </body>
      <footer>
        {/* TODO */}
      </footer>
    </html>
  )
}
